const STORE='macroplan-local-v1';
const meals=['Desayuno','Comida','Merienda','Cena','Otros'];
const days=['lunes','martes','miércoles','jueves','viernes','sábado','domingo'];
const planMeals=['Desayuno','Comida','Merienda','Cena'];
const defaults={goals:{kcal:2100,protein:140,carbs:230,fat:70},entries:[],customFoods:[],usedFoods:[],plan:{}};
let state=load(); let selectedFood=null; let entryMode='grams';
function load(){try{const loaded={...structuredClone(defaults),...JSON.parse(localStorage.getItem(STORE)||'{}')};loaded.usedFoods??=[];for(const e of loaded.entries||[]){if(!e.foodSnapshot&&e.grams>0)e.foodSnapshot={name:e.foodName,brand:'Usado anteriormente',kcal:num(e.nutrients?.kcal)*100/e.grams,protein:num(e.nutrients?.protein)*100/e.grams,carbs:num(e.nutrients?.carbs)*100/e.grams,fat:num(e.nutrients?.fat)*100/e.grams,portions:[]};if(e.foodSnapshot&&!loaded.usedFoods.some(f=>foodKey(f)===foodKey(e.foodSnapshot)))loaded.usedFoods.push({...e.foodSnapshot,lastUsed:e.date,useCount:1})}return loaded}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function num(v){return Number(v)||0}
function round(v,d=0){return Number(v).toFixed(d)}
function isoLocal(d=new Date()){const z=d.getTimezoneOffset()*60000;return new Date(d-z).toISOString().slice(0,10)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function foodKey(food){return `${String(food.name||'').trim().toLowerCase()}|${String(food.brand||'').trim().toLowerCase()}`}
const activeDate=document.querySelector('#activeDate'); activeDate.value=isoLocal();
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function nutrients(food,grams){const f=grams/100;return {kcal:num(food.kcal)*f,protein:num(food.protein)*f,carbs:num(food.carbs)*f,fat:num(food.fat)*f}}
function totals(date){return state.entries.filter(e=>e.date===date).reduce((a,e)=>{for(const k of ['kcal','protein','carbs','fat'])a[k]+=num(e.nutrients[k]);return a},{kcal:0,protein:0,carbs:0,fat:0})}
function renderToday(){const date=activeDate.value;const t=totals(date),g=state.goals;document.querySelector('#todayDate').textContent=new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long'}).format(new Date(date+'T12:00'));
 document.querySelector('#remainingKcal').textContent=Math.round(g.kcal-t.kcal);document.querySelector('#goalKcal').textContent=Math.round(g.kcal);document.querySelector('#usedKcal').textContent=Math.round(t.kcal);const pct=Math.min(100,t.kcal/g.kcal*100);document.querySelector('#calorieRing').style.background=`conic-gradient(#71dec2 ${pct*3.6}deg,#ffffff30 0)`;
 const macros=[['Proteínas','protein','g'],['Carbohidratos','carbs','g'],['Grasas','fat','g']];document.querySelector('#macroCards').innerHTML=macros.map(([label,k,u])=>`<div class="macro-card"><p>${label}</p><strong>${round(t[k],1)} ${u}</strong><span class="muted"> / ${g[k]} ${u}</span><div class="progress"><span style="width:${Math.min(100,t[k]/g[k]*100)}%"></span></div><small class="muted">${round(g[k]-t[k],1)} ${u} restantes</small></div>`).join('');
 document.querySelector('#mealList').innerHTML=meals.map(meal=>{const entries=state.entries.filter(e=>e.date===date&&e.meal===meal),kcal=entries.reduce((a,e)=>a+e.nutrients.kcal,0);return `<article class="meal-card"><div class="meal-head"><h3>${meal}</h3><span>${Math.round(kcal)} kcal</span></div>${entries.length?entries.map(e=>`<div class="entry"><div><strong>${esc(e.foodName)}</strong><small>${round(e.grams,1)} g · ${esc(e.measureLabel)}</small></div><strong>${Math.round(e.nutrients.kcal)} kcal</strong><button data-delete-entry="${e.id}" aria-label="Eliminar">×</button></div>`).join(''):`<div class="meal-empty">Todavía no hay alimentos.</div>`}</article>`}).join('');
 document.querySelectorAll('[data-delete-entry]').forEach(b=>b.onclick=()=>{state.entries=state.entries.filter(e=>e.id!==b.dataset.deleteEntry);save();renderToday();toast('Alimento eliminado')})}
function currentWeek(){const today=new Date(isoLocal()+'T12:00'),monday=new Date(today);monday.setDate(today.getDate()-((today.getDay()+6)%7));return days.map((name,i)=>{const date=new Date(monday);date.setDate(monday.getDate()+i);return {name,iso:isoLocal(date),label:new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short'}).format(date)}})}
function renderPlanner(){const today=isoLocal(),grid=document.querySelector('#weekGrid');grid.innerHTML=currentWeek().map(({name,iso,label})=>{if(iso<today){const actual=state.entries.filter(e=>e.date===iso);return `<article class="day-card past"><h3>${name}</h3><p class="day-date">${label} · Registrado realmente</p>${planMeals.map(meal=>{const list=actual.filter(e=>e.meal===meal);return `<div class="actual-meal"><strong>${meal}</strong>${list.length?list.map(e=>`<p>${esc(e.foodName)} <small>${round(e.grams,1)} g · ${Math.round(e.nutrients.kcal)} kcal</small></p>`).join(''):'<small>Sin registros</small>'}</div>`}).join('')}</article>`}return `<article class="day-card"><h3>${name}</h3><p class="day-date">${label}${iso===today?' · Hoy':' · Planificado'}</p>${planMeals.map(meal=>`<label class="plan-field"><span>${meal}</span><textarea data-plan="${iso}|${meal}" placeholder="¿Qué vas a comer?">${esc(state.plan[iso]?.[meal]||state.plan[name]?.[meal]||'')}</textarea></label>`).join('')}</article>`}).join('');grid.querySelectorAll('textarea').forEach(t=>t.oninput=()=>{const [date,m]=t.dataset.plan.split('|');state.plan[date]??={};state.plan[date][m]=t.value.trim();save()})}
function renderGoals(){const f=document.querySelector('#goalsForm');for(const k of ['kcal','protein','carbs','fat'])f.elements[k].value=state.goals[k]}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='todayView')renderToday();if(id==='plannerView')renderPlanner();if(id==='settingsView')renderGoals();if(id==='foodsView')renderCustomFoods()}
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelector('#settingsButton').onclick=()=>showView('settingsView');activeDate.onchange=renderToday;
document.querySelector('#goalsForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);state.goals={kcal:num(fd.get('kcal')),protein:num(fd.get('protein')),carbs:num(fd.get('carbs')),fat:num(fd.get('fat'))};save();renderToday();toast('Objetivos guardados')};
document.querySelector('#clearPlan').onclick=()=>{if(confirm('¿Quieres borrar toda la planificación semanal?')){state.plan={};save();renderPlanner();toast('Planificación borrada')}};
document.querySelector('#resetData').onclick=()=>{if(confirm('Se borrarán objetivos, registros, alimentos y planificación. ¿Continuar?')){state=structuredClone(defaults);save();activeDate.value=isoLocal();showView('todayView');toast('Datos borrados')}};
function portions(food){const p=[{name:'100 g',grams:100},{name:'1 cucharada',grams:15},{name:'1 taza',grams:200},{name:'1 plato',grams:300},{name:'1 unidad estándar',grams:food.servingGrams||100}];if(food.portions?.length)p.unshift(...food.portions);return p.filter((x,i,a)=>x.grams>0&&a.findIndex(y=>y.name===x.name)===i)}
function openEntry(food,meal='Comida'){selectedFood=food;entryMode='grams';const f=document.querySelector('#foodEntryForm');document.querySelector('#entryFoodName').textContent=food.name;document.querySelector('#entryFoodInfo').textContent=`${food.brand||'Sin marca'} · valores por 100 g`;f.elements.meal.value=meal;f.elements.grams.value=100;f.elements.portionCount.value=1;f.elements.portion.innerHTML=portions(food).map((p,i)=>`<option value="${i}">${esc(p.name)} (${round(p.grams,1)} g)</option>`).join('');setEntryMode('grams');updatePreview();document.querySelector('#foodDialog').showModal()}
function setEntryMode(mode){entryMode=mode;document.querySelector('#gramsMode').hidden=mode!=='grams';document.querySelector('#portionMode').hidden=mode!=='portion';document.querySelectorAll('.segmented button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));updatePreview()}
document.querySelectorAll('.segmented button').forEach(b=>b.onclick=()=>setEntryMode(b.dataset.mode));
function currentGrams(){const f=document.querySelector('#foodEntryForm');if(entryMode==='grams')return num(f.elements.grams.value);const p=portions(selectedFood)[num(f.elements.portion.value)];return num(p?.grams)*num(f.elements.portionCount.value)}
function updatePreview(){if(!selectedFood)return;const g=currentGrams(),n=nutrients(selectedFood,g);document.querySelector('#nutritionPreview').innerHTML=`<strong>${round(g,1)} g</strong> · ${Math.round(n.kcal)} kcal · P ${round(n.protein,1)} g · C ${round(n.carbs,1)} g · G ${round(n.fat,1)} g`}
function rememberFood(food){const clean={name:food.name,brand:food.brand||'',kcal:num(food.kcal),protein:num(food.protein),carbs:num(food.carbs),fat:num(food.fat),image:food.image||'',servingGrams:num(food.servingGrams),portions:food.portions||[]},key=foodKey(clean),existing=state.usedFoods.find(f=>foodKey(f)===key);if(existing)Object.assign(existing,clean,{lastUsed:isoLocal(),useCount:num(existing.useCount)+1});else state.usedFoods.unshift({...clean,lastUsed:isoLocal(),useCount:1});return clean}
document.querySelector('#foodEntryForm').oninput=updatePreview;document.querySelector('#foodEntryForm').onsubmit=e=>{e.preventDefault();const g=currentGrams();if(g<=0)return;const f=e.target,p=entryMode==='portion'?portions(selectedFood)[num(f.elements.portion.value)]:null,foodSnapshot=rememberFood(selectedFood);state.entries.push({id:crypto.randomUUID(),date:activeDate.value,meal:f.elements.meal.value,foodName:selectedFood.name,grams:g,measureLabel:entryMode==='grams'?`${round(g,1)} gramos`:`${f.elements.portionCount.value} × ${p.name}`,nutrients:nutrients(selectedFood,g),foodSnapshot});save();document.querySelector('#foodDialog').close();showView('todayView');toast('Añadido y guardado en tus habituales')};
const sampleFoods=[{name:'Plátano',brand:'Alimento básico',kcal:89,protein:1.1,carbs:22.8,fat:.3,portions:[{name:'1 plátano mediano',grams:120}]},{name:'Arroz blanco cocido',brand:'Alimento básico',kcal:130,protein:2.7,carbs:28.2,fat:.3,portions:[{name:'1 taza cocida',grams:180},{name:'1 plato',grams:250}]},{name:'Pechuga de pollo cocinada',brand:'Alimento básico',kcal:165,protein:31,carbs:0,fat:3.6,portions:[{name:'1 filete mediano',grams:150}]},{name:'Aceite de oliva',brand:'Alimento básico',kcal:884,protein:0,carbs:0,fat:100,portions:[{name:'1 cucharada',grams:10},{name:'1 cucharadita',grams:5}]},{name:'Huevo de gallina',brand:'Alimento básico',kcal:143,protein:12.6,carbs:.7,fat:9.5,portions:[{name:'1 huevo mediano',grams:60}]}];
function foodCard(f,i,kind='result'){return `<article class="food-card">${f.image?`<img src="${esc(f.image)}" alt="">`:`<div class="food-placeholder">🍽</div>`}<div class="food-info"><h3>${esc(f.name)}</h3><p>${esc(f.brand||'Sin marca')}</p><p>${Math.round(f.kcal)} kcal · P ${round(f.protein,1)} · C ${round(f.carbs,1)} · G ${round(f.fat,1)}</p></div><button class="primary" data-food-index="${i}" data-food-kind="${kind}">Añadir</button></article>`}
function bindFoodButtons(collection,kind){document.querySelectorAll(`[data-food-kind="${kind}"]`).forEach(b=>b.onclick=()=>openEntry(collection[num(b.dataset.foodIndex)]))}
function myFoods(){const seen=new Set();return [...state.usedFoods].sort((a,b)=>num(b.useCount)-num(a.useCount)).concat(state.customFoods,sampleFoods).filter(f=>{const k=foodKey(f);if(seen.has(k))return false;seen.add(k);return true})}
function renderCustomFoods(query=''){const q=query.trim().toLowerCase(),all=myFoods().filter(f=>!q||`${f.name} ${f.brand||''}`.toLowerCase().includes(q)),count=state.usedFoods.length;document.querySelector('#searchStatus').textContent=count?`${count} ${count===1?'alimento guardado':'alimentos guardados'} automáticamente de tu diario.`:'Cuando añadas un alimento al diario, se guardará aquí automáticamente.';document.querySelector('#foodResults').innerHTML=all.length?all.map((f,i)=>foodCard(f,i,'local')).join(''):'<div class="empty-state">No hay coincidencias en tus alimentos habituales.</div>';bindFoodButtons(all,'local')}
document.querySelector('#customFoodButton').onclick=()=>document.querySelector('#customFoodDialog').showModal();
document.querySelector('#customFoodForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target),pn=String(d.get('portionName')||'').trim(),pg=num(d.get('portionGrams'));const food={name:String(d.get('name')).trim(),brand:String(d.get('brand')).trim(),kcal:num(d.get('kcal')),protein:num(d.get('protein')),carbs:num(d.get('carbs')),fat:num(d.get('fat')),portions:pn&&pg?[{name:pn,grams:pg}]:[]};state.customFoods.unshift(food);save();e.target.reset();document.querySelector('#customFoodDialog').close();renderCustomFoods();toast('Alimento guardado')};
document.querySelector('#searchForm').onsubmit=async e=>{e.preventDefault();const q=document.querySelector('#searchInput').value.trim(),scope=document.querySelector('#searchScope').value;if(scope==='mine'){renderCustomFoods(q);return}if(q.length<2)return toast('Escribe al menos 2 caracteres');const status=document.querySelector('#searchStatus'),box=document.querySelector('#foodResults');status.textContent='Buscando productos…';box.innerHTML='';try{const url=`https://world.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(q)}&search_simple=1&action=process&json=1&page_size=20&countries_tags_en=spain&fields=code,product_name,brands,image_front_small_url,nutriments,serving_quantity,serving_size`;
 const res=await fetch(url);if(!res.ok)throw Error('HTTP');const json=await res.json();const found=(json.products||[]).map(p=>({name:p.product_name||'Producto sin nombre',brand:p.brands||'',image:p.image_front_small_url||'',kcal:num(p.nutriments?.['energy-kcal_100g']),protein:num(p.nutriments?.proteins_100g),carbs:num(p.nutriments?.carbohydrates_100g),fat:num(p.nutriments?.fat_100g),servingGrams:num(p.serving_quantity)})).filter(p=>p.name&&p.kcal>0);status.textContent=found.length?`${found.length} productos encontrados en OpenFoodFacts.`:'No se encontraron productos con datos nutricionales.';box.innerHTML=found.map((f,i)=>foodCard(f,i,'online')).join('');bindFoodButtons(found,'online')}catch{status.textContent='No se pudo conectar con OpenFoodFacts. Puedes usar los alimentos locales o crear uno manualmente.';renderCustomFoods()}};
document.querySelector('#quickAdd').onclick=()=>{showView('foodsView')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.querySelector('#'+b.dataset.close).close());
renderToday();renderGoals();
if('serviceWorker' in navigator&&location.protocol.startsWith('http')){window.addEventListener('load',async()=>{try{const registration=await navigator.serviceWorker.register('./sw.js');registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)toast('MacroPlan se ha actualizado')})})}catch{}})}
